// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfalsaauwanevzrqaoaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmYWxzYWF1d2FuZXZ6cnFhb2FhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2OTE2MzksImV4cCI6MjA2NzI2NzYzOX0.hwbtIIJaxibliUb1K73sR1S8yCn9bh7e2r-vBhk3VdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});